spring:
  profiles:
    active: development
PayConstant:
  mustUseFrontNotifyForOrderStatus: true
  mustUseFrontNotifyForInventory: true
  mustUseBackNotifyForOrderStatus: true
  mustUseBackNotifyForInventory:  false
QrcbConstant:
  sync_success: 000000
#  partner: 12052737
#  key: fd27ea9125c84c1886d0a4a7a94c211d
  show_url: https://sqyx.qrcb.com.cn/
  url: https://epay.qrcb.com.cn:50080/epaygate/mb/Wirelesspaygate.htm
#  return_url: https://sqyx.qrcb.com.cn/html/shoppingcart/payresult.html?outTradeNo=
#  notify_url: https://sqyx.qrcb.com.cn/api/trade/nologin/backRcvResp/
---
spring:
  profiles: development
  datasource:
    url: jdbc:oracle:thin:@db.openec.zyhao.com:1521:orclsqyx
    username: orderdb
    password: sqyx123
    initialize: false
  zipkin:
    base-url: http://zipkin.openec.zyhao.com:9411/
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
security:
  oauth2:
    resource:
      userInfoUri: http://user.openec.zyhao.com:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://user.openec.zyhao.com:8787
  ignored: /**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.openec.zyhao.com:8761/eureka/
